# Generated by Django 5.2.7 on 2025-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
