# Generated by Django 5.2.7 on 2025-10-25 12:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='mentions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
